### ISSUE TITLE
pywix only works with Python 3+

### ISSUE THREAD

**Issue by mbrennan** [xoviat/pywix#4]
Several Python 2.7 package depend on pywix, such as [subzero](https://pypi.python.org/pypi/subzero).  If one tries to install pywix on a Python 2.7-based interpreter, the following exception occurs:

> Collecting pywix
>  Downloading pywix-0.2.1.tar.gz
>    Complete output from command python setup.py egg_info:
>    Traceback (most recent call last):
>      File "<string>", line 1, in <module>
>      File "[...]setup.py", line 10, in <module>
>        from go_msi import find_go_msi, find_wix_toolset
>      File "go_msi\__init__.py", line 60, in <module>
>        @functools.lru_cache(maxsize=128)
>    AttributeError: 'module' object has no attribute 'lru_cache'

On Python 2.7, could pywix depend on [functools32](https://pypi.python.org/pypi/functools32), which includes lru_cache?

**Comment by xoviat** [comment]
See pywin32/pypiwin32#68 for my opinion of Python 2.7.

**Comment by mbrennan** [comment]
That's fine, but can you mark the package appropriately so it requires Python 3?  It'd be better to have the installation fail rather than the next guy or gal try to figure out why it's not working with Python 2.7.

**Comment by xoviat** [comment]
Subzero doesn't have a wheel for Python 2. Do you want me to add a Python 3 tag on Github?

**Comment by mbrennan** [comment]
You can add a Python 3 environment marker to the setup.py: https://www.python.org/dev/peps/pep-0508/#environment-markers .  That way any source installation should fail unless using Python 3 too.
